baseURL = "/"
languageCode = "en-us"
title = "ENMU CS Club"
theme = "archie"
pygmentsstyle = "material"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 4

[params]
favicon = "https://img.icons8.com/officel/16/000000/chevron-right.png"
# mode = "auto"
mode = "toggle"
useCDN = true
subtitle = "Computer Science Club at Eastern New Mexico University"

#[[params.social]]
#name = "GitHub"
#icon = "github"
#url = "https://github.com/athul/archie"

#[[params.social]]
#name = "Twitter"
#icon = "twitter"
#url = "https://github.com/athulcajay/"

#[[params.social]]
#name = "GitLab"
#icon = "gitlab"
#url = "https://gitlab.com/athul/"

[[params.social]]
name = "RSS"
icon = "rss"
link = "/index.xml"

[[params.social]]
name = "Email"
icon = "mail"
link = "renata.torrez@enmu.edu"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Classifieds"
url = "/classifieds"
weight = 3

[[menu.main]]
name = "Officers"
url = "/officers"
weight = 4


[[menu.main]]
name = "About"
url = "/about"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 6

